# This is a basic workflow to help you get started with Actions

name: Cypress end-to-end tests

# Controls when the workflow will run

on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 cypress-run:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
            node-version: '14'
      - name: Install dependencies
        run: npm install       
      - name: Cypress run
        uses: cypress-io/github-action@v2



