# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run

on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'v14'
          
      - name: Install our dependencies
        run: npm ci # Faster than npm install, does the same thing
      - name: start server
        run: npm start
      - name: start tests
        run: npm test
